services:
  iptv-hub:
    build: .
    container_name: iptv-hub
    network_mode: "host"
    restart: always
    ports:
      - "2022:2022"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # --- NEU: Logging Limits hinzugefügt ---
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximal 10 MB pro Log-Datei
        max-file: "3"     # Maximal 3 alte Dateien behalten
